modLoader="javafml"
loaderVersion="[36,)"
license="MIT"

[[mods]]
modId="skyfarm"
version="1.0.2"
displayName="Sky Farm"
updateJSONURL="https://raw.githubusercontent.com/North-West-Wind/SkyFarmEssential/main/update.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/sky-farm-stuff"
logoFile="skyfarm.png"
itemIcon="skyfarm:natural_evaporator"
credits="Thank you to Sky Factory 4 for being amazing"
authors="NorthWestWind"
description='''
An essential mod for NorthWestWind's Sky Farm modpack.
'''

[[dependencies.skyfarm]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.skyfarm]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"

[[dependencies.skyfarm]]
    modId="mekanism"
    mandatory=true
    versionRange="[10.0.21,)"
    ordering="NONE"
    side="BOTH"