// Put in data/skyfarm/advancements/farming

const fs = require("fs");
const json = require("./crops.json");

function addCrops(shortname, isTree = false) {
    json.criteria[shortname] = {
        "trigger": "minecraft:inventory_changed",
        "conditions": {
            "items": [{ "item": `${isTree ? "pamhc2trees" : "pamhc2crops"}:${shortname}item` }]
        }
    };
    json.requirements.push([shortname]);
}
addCrops("quinoa");
addCrops("rice");
addCrops("rye");
addCrops("soybean");
addCrops("cotton");
addCrops("flax");
addCrops("kenaf");
addCrops("jute");
addCrops("sisal");
addCrops("artichoke");
addCrops("asparagus");
addCrops("bellpepper");
addCrops("broccoli");
addCrops("brusselsprout");
addCrops("cabbage");
addCrops("cauliflower");
addCrops("celery");
addCrops("chilipepper");
addCrops("cucumber");
addCrops("eggplant");
addCrops("kale");
addCrops("lettuce");
addCrops("okra");
addCrops("peas");
addCrops("spinach");
addCrops("tomatillo");
addCrops("tomato");
addCrops("wintersquash");
addCrops("zucchini");
addCrops("arrowroot");
addCrops("cassava");
addCrops("garlic");
addCrops("jicama");
addCrops("leek");
addCrops("kohlrabi");
addCrops("onion");
addCrops("parsnip");
addCrops("peanut");
addCrops("radish");
addCrops("rhubarb");
addCrops("rutabaga");
addCrops("scallion");
addCrops("sweetpotato");
addCrops("taro");
addCrops("turnip");
addCrops("waterchestnut");
addCrops("blackberry");
addCrops("blueberry");
addCrops("cactusfruit");
addCrops("candleberry");
addCrops("cantaloupe");
addCrops("cranberry");
addCrops("elderberry");
addCrops("grape");
addCrops("greengrape");
addCrops("huckleberry");
addCrops("juniperberry");
addCrops("kiwi");
addCrops("mulberry");
addCrops("pineapple");
addCrops("easpberry");
addCrops("strawberry");
addCrops("coffeebean");
addCrops("tealeaf");
addCrops("agave");
addCrops("whitemushroom");
addCrops("ginger");
addCrops("sesameseeds");
addCrops("spiceleaf");
addCrops("mustardseeds");
addCrops("avocado", true);
addCrops("candlenut", true);
addCrops("cherry", true);
addCrops("chestnut", true);
addCrops("gooseberry", true);
addCrops("lemon", true);
addCrops("nutmeg", true);
addCrops("orange", true);
addCrops("peach", true);
addCrops("pear", true);
addCrops("plum", true);
addCrops("walnut", true);
addCrops("hazelnut", true);
addCrops("pawpaw", true);
addCrops("soursop", true);
addCrops("almond", true);
addCrops("apricot", true);
addCrops("banana", true);
addCrops("cashew", true);
addCrops("cinnamon", true);
addCrops("coconut", true);
addCrops("date", true);
addCrops("dragonfruit", true);
addCrops("durian", true);
addCrops("fig", true);
addCrops("grapefruit", true);
addCrops("lime", true);
addCrops("mango", true);
addCrops("olive", true);
addCrops("papaya", true);
addCrops("pecan", true);
addCrops("peppercorn", true);
addCrops("persimmon", true);
addCrops("pistachio", true);
addCrops("pomegranate", true);
addCrops("starfruit", true);
addCrops("vanillabean", true);
addCrops("breadfruit", true);
addCrops("guava", true);
addCrops("jackfruit", true);
addCrops("lychee", true);
addCrops("passionfruit", true);
addCrops("rambutan", true);
addCrops("tamarind", true);
addCrops("maplesyrup", true);
addCrops("pinenut", true);

fs.writeFileSync("./crops.json", JSON.stringify(json, null, 2));