val mysticalagriculture_air = crops.getCrops("mysticalagriculture:crops/air");
mysticalagriculture_air.addCategory("dirt");
val mysticalagriculture_aluminum = crops.getCrops("mysticalagriculture:crops/aluminum");
mysticalagriculture_aluminum.addCategory("dirt");
val mysticalagriculture_aquamarine = crops.getCrops("mysticalagriculture:crops/aquamarine");
mysticalagriculture_aquamarine.addCategory("dirt");
val mysticalagriculture_basalz = crops.getCrops("mysticalagriculture:crops/basalz");
mysticalagriculture_basalz.addCategory("dirt");
val mysticalagriculture_blaze = crops.getCrops("mysticalagriculture:crops/blaze");
mysticalagriculture_blaze.addCategory("dirt");
val mysticalagriculture_blazing_crystal = crops.getCrops("mysticalagriculture:crops/blazing_crystal");
mysticalagriculture_blazing_crystal.addCategory("dirt");
val mysticalagriculture_blitz = crops.getCrops("mysticalagriculture:crops/blitz");
mysticalagriculture_blitz.addCategory("dirt");
val mysticalagriculture_blizz = crops.getCrops("mysticalagriculture:crops/blizz");
mysticalagriculture_blizz.addCategory("dirt");
val mysticalagriculture_brass = crops.getCrops("mysticalagriculture:crops/brass");
mysticalagriculture_brass.addCategory("dirt");
val mysticalagriculture_bronze = crops.getCrops("mysticalagriculture:crops/bronze");
mysticalagriculture_bronze.addCategory("dirt");
val mysticalagriculture_certus_quartz = crops.getCrops("mysticalagriculture:crops/certus_quartz");
mysticalagriculture_certus_quartz.addCategory("dirt");
val mysticalagriculture_chicken = crops.getCrops("mysticalagriculture:crops/chicken");
mysticalagriculture_chicken.addCategory("dirt");
val mysticalagriculture_chrome = crops.getCrops("mysticalagriculture:crops/chrome");
mysticalagriculture_chrome.addCategory("dirt");
val mysticalagriculture_coal = crops.getCrops("mysticalagriculture:crops/coal");
mysticalagriculture_coal.addCategory("dirt");
val mysticalagriculture_compressed_iron = crops.getCrops("mysticalagriculture:crops/compressed_iron");
mysticalagriculture_compressed_iron.addCategory("dirt");
val mysticalagriculture_constantan = crops.getCrops("mysticalagriculture:crops/constantan");
mysticalagriculture_constantan.addCategory("dirt");
val mysticalagriculture_copper = crops.getCrops("mysticalagriculture:crops/copper");
mysticalagriculture_copper.addCategory("dirt");
val mysticalagriculture_coral = crops.getCrops("mysticalagriculture:crops/coral");
mysticalagriculture_coral.addCategory("dirt");
val mysticalagriculture_cow = crops.getCrops("mysticalagriculture:crops/cow");
mysticalagriculture_cow.addCategory("dirt");
val mysticalagriculture_creeper = crops.getCrops("mysticalagriculture:crops/creeper");
mysticalagriculture_creeper.addCategory("dirt");
val mysticalagriculture_cyanite = crops.getCrops("mysticalagriculture:crops/cyanite");
mysticalagriculture_cyanite.addCategory("dirt");
val mysticalagriculture_diamond = crops.getCrops("mysticalagriculture:crops/diamond");
mysticalagriculture_diamond.addCategory("dirt");
val mysticalagriculture_dirt = crops.getCrops("mysticalagriculture:crops/dirt");
mysticalagriculture_dirt.addCategory("dirt");
val mysticalagriculture_dragon_egg = crops.getCrops("mysticalagriculture:crops/dragon_egg");
mysticalagriculture_dragon_egg.addCategory("dirt");
val mysticalagriculture_dye = crops.getCrops("mysticalagriculture:crops/dye");
mysticalagriculture_dye.addCategory("dirt");
val mysticalagriculture_earth = crops.getCrops("mysticalagriculture:crops/earth");
mysticalagriculture_earth.addCategory("dirt");
val mysticalagriculture_electrum = crops.getCrops("mysticalagriculture:crops/electrum");
mysticalagriculture_electrum.addCategory("dirt");
val mysticalagriculture_elementium = crops.getCrops("mysticalagriculture:crops/elementium");
mysticalagriculture_elementium.addCategory("dirt");
val mysticalagriculture_emerald = crops.getCrops("mysticalagriculture:crops/emerald");
mysticalagriculture_emerald.addCategory("dirt");
val mysticalagriculture_end = crops.getCrops("mysticalagriculture:crops/end");
mysticalagriculture_end.addCategory("dirt");
val mysticalagriculture_enderium = crops.getCrops("mysticalagriculture:crops/enderium");
mysticalagriculture_enderium.addCategory("dirt");
val mysticalagriculture_enderman = crops.getCrops("mysticalagriculture:crops/enderman");
mysticalagriculture_enderman.addCategory("dirt");
val mysticalagriculture_ender_biotite = crops.getCrops("mysticalagriculture:crops/ender_biotite");
mysticalagriculture_ender_biotite.addCategory("dirt");
val mysticalagriculture_energized_steel = crops.getCrops("mysticalagriculture:crops/energized_steel");
mysticalagriculture_energized_steel.addCategory("dirt");
val mysticalagriculture_experience = crops.getCrops("mysticalagriculture:crops/experience");
mysticalagriculture_experience.addCategory("dirt");
val mysticalagriculture_fire = crops.getCrops("mysticalagriculture:crops/fire");
mysticalagriculture_fire.addCategory("dirt");
val mysticalagriculture_fish = crops.getCrops("mysticalagriculture:crops/fish");
mysticalagriculture_fish.addCategory("dirt");
val mysticalagriculture_fluix = crops.getCrops("mysticalagriculture:crops/fluix");
mysticalagriculture_fluix.addCategory("dirt");
val mysticalagriculture_ghast = crops.getCrops("mysticalagriculture:crops/ghast");
mysticalagriculture_ghast.addCategory("dirt");
val mysticalagriculture_glowstone = crops.getCrops("mysticalagriculture:crops/glowstone");
mysticalagriculture_glowstone.addCategory("dirt");
val mysticalagriculture_gold = crops.getCrops("mysticalagriculture:crops/gold");
mysticalagriculture_gold.addCategory("dirt");
val mysticalagriculture_graphite = crops.getCrops("mysticalagriculture:crops/graphite");
mysticalagriculture_graphite.addCategory("dirt");
val mysticalagriculture_honey = crops.getCrops("mysticalagriculture:crops/honey");
mysticalagriculture_honey.addCategory("dirt");
val mysticalagriculture_hop_graphite = crops.getCrops("mysticalagriculture:crops/hop_graphite");
mysticalagriculture_hop_graphite.addCategory("dirt");
val mysticalagriculture_ice = crops.getCrops("mysticalagriculture:crops/ice");
mysticalagriculture_ice.addCategory("dirt");
val mysticalagriculture_inferium = crops.getCrops("mysticalagriculture:crops/inferium");
mysticalagriculture_inferium.addCategory("dirt");
val mysticalagriculture_invar = crops.getCrops("mysticalagriculture:crops/invar");
mysticalagriculture_invar.addCategory("dirt");
val mysticalagriculture_iridium = crops.getCrops("mysticalagriculture:crops/iridium");
mysticalagriculture_iridium.addCategory("dirt");
val mysticalagriculture_iron = crops.getCrops("mysticalagriculture:crops/iron");
mysticalagriculture_iron.addCategory("dirt");
val mysticalagriculture_lapis_lazuli = crops.getCrops("mysticalagriculture:crops/lapis_lazuli");
mysticalagriculture_lapis_lazuli.addCategory("dirt");
val mysticalagriculture_lead = crops.getCrops("mysticalagriculture:crops/lead");
mysticalagriculture_lead.addCategory("dirt");
val mysticalagriculture_lumium = crops.getCrops("mysticalagriculture:crops/lumium");
mysticalagriculture_lumium.addCategory("dirt");
val mysticalagriculture_manasteel = crops.getCrops("mysticalagriculture:crops/manasteel");
mysticalagriculture_manasteel.addCategory("dirt");
val mysticalagriculture_mithril = crops.getCrops("mysticalagriculture:crops/mithril");
mysticalagriculture_mithril.addCategory("dirt");
val mysticalagriculture_mystical_flower = crops.getCrops("mysticalagriculture:crops/mystical_flower");
mysticalagriculture_mystical_flower.addCategory("dirt");
val mysticalagriculture_nature = crops.getCrops("mysticalagriculture:crops/nature");
mysticalagriculture_nature.addCategory("dirt");
val mysticalagriculture_nether = crops.getCrops("mysticalagriculture:crops/nether");
mysticalagriculture_nether.addCategory("dirt");
val mysticalagriculture_netherite = crops.getCrops("mysticalagriculture:crops/netherite");
mysticalagriculture_netherite.addCategory("dirt");
val mysticalagriculture_nether_quartz = crops.getCrops("mysticalagriculture:crops/nether_quartz");
mysticalagriculture_nether_quartz.addCategory("dirt");
val mysticalagriculture_nether_star = crops.getCrops("mysticalagriculture:crops/nether_star");
mysticalagriculture_nether_star.addCategory("dirt");
val mysticalagriculture_nickel = crops.getCrops("mysticalagriculture:crops/nickel");
mysticalagriculture_nickel.addCategory("dirt");
val mysticalagriculture_niotic_crystal = crops.getCrops("mysticalagriculture:crops/niotic_crystal");
mysticalagriculture_niotic_crystal.addCategory("dirt");
val mysticalagriculture_obsidian = crops.getCrops("mysticalagriculture:crops/obsidian");
mysticalagriculture_obsidian.addCategory("dirt");
val mysticalagriculture_osmium = crops.getCrops("mysticalagriculture:crops/osmium");
mysticalagriculture_osmium.addCategory("dirt");
val mysticalagriculture_pig = crops.getCrops("mysticalagriculture:crops/pig");
mysticalagriculture_pig.addCategory("dirt");
val mysticalagriculture_platinum = crops.getCrops("mysticalagriculture:crops/platinum");
mysticalagriculture_platinum.addCategory("dirt");
val mysticalagriculture_prismarine = crops.getCrops("mysticalagriculture:crops/prismarine");
mysticalagriculture_prismarine.addCategory("dirt");
val mysticalagriculture_quartz_enriched_iron = crops.getCrops("mysticalagriculture:crops/quartz_enriched_iron");
mysticalagriculture_quartz_enriched_iron.addCategory("dirt");
val mysticalagriculture_rabbit = crops.getCrops("mysticalagriculture:crops/rabbit");
mysticalagriculture_rabbit.addCategory("dirt");
val mysticalagriculture_redstone = crops.getCrops("mysticalagriculture:crops/redstone");
mysticalagriculture_redstone.addCategory("dirt");
val mysticalagriculture_refined_glowstone = crops.getCrops("mysticalagriculture:crops/refined_glowstone");
mysticalagriculture_refined_glowstone.addCategory("dirt");
val mysticalagriculture_refined_obsidian = crops.getCrops("mysticalagriculture:crops/refined_obsidian");
mysticalagriculture_refined_obsidian.addCategory("dirt");
val mysticalagriculture_rock_crystal = crops.getCrops("mysticalagriculture:crops/rock_crystal");
mysticalagriculture_rock_crystal.addCategory("dirt");
val mysticalagriculture_rubber = crops.getCrops("mysticalagriculture:crops/rubber");
mysticalagriculture_rubber.addCategory("dirt");
val mysticalagriculture_saltpeter = crops.getCrops("mysticalagriculture:crops/saltpeter");
mysticalagriculture_saltpeter.addCategory("dirt");
val mysticalagriculture_sheep = crops.getCrops("mysticalagriculture:crops/sheep");
mysticalagriculture_sheep.addCategory("dirt");
val mysticalagriculture_signalum = crops.getCrops("mysticalagriculture:crops/signalum");
mysticalagriculture_signalum.addCategory("dirt");
val mysticalagriculture_silicon = crops.getCrops("mysticalagriculture:crops/silicon");
mysticalagriculture_silicon.addCategory("dirt");
val mysticalagriculture_silver = crops.getCrops("mysticalagriculture:crops/silver");
mysticalagriculture_silver.addCategory("dirt");
val mysticalagriculture_skeleton = crops.getCrops("mysticalagriculture:crops/skeleton");
mysticalagriculture_skeleton.addCategory("dirt");
val mysticalagriculture_sky_stone = crops.getCrops("mysticalagriculture:crops/sky_stone");
mysticalagriculture_sky_stone.addCategory("dirt");
val mysticalagriculture_slime = crops.getCrops("mysticalagriculture:crops/slime");
mysticalagriculture_slime.addCategory("dirt");
val mysticalagriculture_spider = crops.getCrops("mysticalagriculture:crops/spider");
mysticalagriculture_spider.addCategory("dirt");
val mysticalagriculture_spirited_crystal = crops.getCrops("mysticalagriculture:crops/spirited_crystal");
mysticalagriculture_spirited_crystal.addCategory("dirt");
val mysticalagriculture_squid = crops.getCrops("mysticalagriculture:crops/squid");
mysticalagriculture_squid.addCategory("dirt");
val mysticalagriculture_starmetal = crops.getCrops("mysticalagriculture:crops/starmetal");
mysticalagriculture_starmetal.addCategory("dirt");
val mysticalagriculture_steel = crops.getCrops("mysticalagriculture:crops/steel");
mysticalagriculture_steel.addCategory("dirt");
val mysticalagriculture_stone = crops.getCrops("mysticalagriculture:crops/stone");
mysticalagriculture_stone.addCategory("dirt");
val mysticalagriculture_sulfur = crops.getCrops("mysticalagriculture:crops/sulfur");
mysticalagriculture_sulfur.addCategory("dirt");
val mysticalagriculture_terrasteel = crops.getCrops("mysticalagriculture:crops/terrasteel");
mysticalagriculture_terrasteel.addCategory("dirt");
val mysticalagriculture_tin = crops.getCrops("mysticalagriculture:crops/tin");
mysticalagriculture_tin.addCategory("dirt");
val mysticalagriculture_titanium = crops.getCrops("mysticalagriculture:crops/titanium");
mysticalagriculture_titanium.addCategory("dirt");
val mysticalagriculture_tungsten = crops.getCrops("mysticalagriculture:crops/tungsten");
mysticalagriculture_tungsten.addCategory("dirt");
val mysticalagriculture_turtle = crops.getCrops("mysticalagriculture:crops/turtle");
mysticalagriculture_turtle.addCategory("dirt");
val mysticalagriculture_uraninite = crops.getCrops("mysticalagriculture:crops/uraninite");
mysticalagriculture_uraninite.addCategory("dirt");
val mysticalagriculture_uranium = crops.getCrops("mysticalagriculture:crops/uranium");
mysticalagriculture_uranium.addCategory("dirt");
val mysticalagriculture_water = crops.getCrops("mysticalagriculture:crops/water");
mysticalagriculture_water.addCategory("dirt");
val mysticalagriculture_wither_skeleton = crops.getCrops("mysticalagriculture:crops/wither_skeleton");
mysticalagriculture_wither_skeleton.addCategory("dirt");
val mysticalagriculture_wood = crops.getCrops("mysticalagriculture:crops/wood");
mysticalagriculture_wood.addCategory("dirt");
val mysticalagriculture_yellorium = crops.getCrops("mysticalagriculture:crops/yellorium");
mysticalagriculture_yellorium.addCategory("dirt");
val mysticalagriculture_zinc = crops.getCrops("mysticalagriculture:crops/zinc");
mysticalagriculture_zinc.addCategory("dirt");
val mysticalagriculture_zombie = crops.getCrops("mysticalagriculture:crops/zombie");
mysticalagriculture_zombie.addCategory("dirt");