val mysticalagriculture_air = crops.getCrop("mysticalagriculture:crops/air");
mysticalagriculture_air.clearDrops();
mysticalagriculture_air.addCategory("dirt");
mysticalagriculture_air.addDrop(<item:mysticalagriculture:air_essence>, 0.5, 4);
mysticalagriculture_air.addDrop(<item:mysticalagriculture:air_seeds>, 0.2);
mysticalagriculture_air.addDrop(<item:mysticalagriculture:fertilized_essence>, 0.01, 1);
val mysticalagriculture_aluminum = crops.getCrop("mysticalagriculture:crops/aluminum");
mysticalagriculture_aluminum.clearDrops();
mysticalagriculture_aluminum.addCategory("dirt");
mysticalagriculture_aluminum.addDrop(<item:mysticalagriculture:aluminum_essence>, 0.5, 4);
mysticalagriculture_aluminum.addDrop(<item:mysticalagriculture:aluminum_seeds>, 0.2);
mysticalagriculture_aluminum.addDrop(<item:mysticalagriculture:fertilized_essence>, 0.01, 1);
val mysticalagriculture_basalz = crops.getCrop("mysticalagriculture:crops/basalz");
mysticalagriculture_basalz.clearDrops();
mysticalagriculture_basalz.addCategory("dirt");
mysticalagriculture_basalz.addDrop(<item:mysticalagriculture:basalz_essence>, 0.5, 4);
mysticalagriculture_basalz.addDrop(<item:mysticalagriculture:basalz_seeds>, 0.2);
mysticalagriculture_basalz.addDrop(<item:mysticalagriculture:fertilized_essence>, 0.01, 1);
val mysticalagriculture_blaze = crops.getCrop("mysticalagriculture:crops/blaze");
mysticalagriculture_blaze.clearDrops();
mysticalagriculture_blaze.addCategory("dirt");
mysticalagriculture_blaze.addDrop(<item:mysticalagriculture:blaze_essence>, 0.5, 4);
mysticalagriculture_blaze.addDrop(<item:mysticalagriculture:blaze_seeds>, 0.2);
mysticalagriculture_blaze.addDrop(<item:mysticalagriculture:fertilized_essence>, 0.01, 1);
val mysticalagriculture_blazing_crystal = crops.getCrop("mysticalagriculture:crops/blazing_crystal");
mysticalagriculture_blazing_crystal.clearDrops();
mysticalagriculture_blazing_crystal.addCategory("dirt");
mysticalagriculture_blazing_crystal.addDrop(<item:mysticalagriculture:blazing_crystal_essence>, 0.5, 4);
mysticalagriculture_blazing_crystal.addDrop(<item:mysticalagriculture:blazing_crystal_seeds>, 0.2);
mysticalagriculture_blazing_crystal.addDrop(<item:mysticalagriculture:fertilized_essence>, 0.01, 1);
val mysticalagriculture_blitz = crops.getCrop("mysticalagriculture:crops/blitz");
mysticalagriculture_blitz.clearDrops();
mysticalagriculture_blitz.addCategory("dirt");
mysticalagriculture_blitz.addDrop(<item:mysticalagriculture:blitz_essence>, 0.5, 4);
mysticalagriculture_blitz.addDrop(<item:mysticalagriculture:blitz_seeds>, 0.2);
mysticalagriculture_blitz.addDrop(<item:mysticalagriculture:fertilized_essence>, 0.01, 1);
val mysticalagriculture_blizz = crops.getCrop("mysticalagriculture:crops/blizz");
mysticalagriculture_blizz.clearDrops();
mysticalagriculture_blizz.addCategory("dirt");
mysticalagriculture_blizz.addDrop(<item:mysticalagriculture:blizz_essence>, 0.5, 4);
mysticalagriculture_blizz.addDrop(<item:mysticalagriculture:blizz_seeds>, 0.2);
mysticalagriculture_blizz.addDrop(<item:mysticalagriculture:fertilized_essence>, 0.01, 1);
val mysticalagriculture_brass = crops.getCrop("mysticalagriculture:crops/brass");
mysticalagriculture_brass.clearDrops();
mysticalagriculture_brass.addCategory("dirt");
mysticalagriculture_brass.addDrop(<item:mysticalagriculture:brass_essence>, 0.5, 4);
mysticalagriculture_brass.addDrop(<item:mysticalagriculture:brass_seeds>, 0.2);
mysticalagriculture_brass.addDrop(<item:mysticalagriculture:fertilized_essence>, 0.01, 1);
val mysticalagriculture_bronze = crops.getCrop("mysticalagriculture:crops/bronze");
mysticalagriculture_bronze.clearDrops();
mysticalagriculture_bronze.addCategory("dirt");
mysticalagriculture_bronze.addDrop(<item:mysticalagriculture:bronze_essence>, 0.5, 4);
mysticalagriculture_bronze.addDrop(<item:mysticalagriculture:bronze_seeds>, 0.2);
mysticalagriculture_bronze.addDrop(<item:mysticalagriculture:fertilized_essence>, 0.01, 1);
val mysticalagriculture_certus_quartz = crops.getCrop("mysticalagriculture:crops/certus_quartz");
mysticalagriculture_certus_quartz.clearDrops();
mysticalagriculture_certus_quartz.addCategory("dirt");
mysticalagriculture_certus_quartz.addDrop(<item:mysticalagriculture:certus_quartz_essence>, 0.5, 4);
mysticalagriculture_certus_quartz.addDrop(<item:mysticalagriculture:certus_quartz_seeds>, 0.2);
mysticalagriculture_certus_quartz.addDrop(<item:mysticalagriculture:fertilized_essence>, 0.01, 1);
val mysticalagriculture_chicken = crops.getCrop("mysticalagriculture:crops/chicken");
mysticalagriculture_chicken.clearDrops();
mysticalagriculture_chicken.addCategory("dirt");
mysticalagriculture_chicken.addDrop(<item:mysticalagriculture:chicken_essence>, 0.5, 4);
mysticalagriculture_chicken.addDrop(<item:mysticalagriculture:chicken_seeds>, 0.2);
mysticalagriculture_chicken.addDrop(<item:mysticalagriculture:fertilized_essence>, 0.01, 1);
val mysticalagriculture_coal = crops.getCrop("mysticalagriculture:crops/coal");
mysticalagriculture_coal.clearDrops();
mysticalagriculture_coal.addCategory("dirt");
mysticalagriculture_coal.addDrop(<item:mysticalagriculture:coal_essence>, 0.5, 4);
mysticalagriculture_coal.addDrop(<item:mysticalagriculture:coal_seeds>, 0.2);
mysticalagriculture_coal.addDrop(<item:mysticalagriculture:fertilized_essence>, 0.01, 1);
val mysticalagriculture_compressed_iron = crops.getCrop("mysticalagriculture:crops/compressed_iron");
mysticalagriculture_compressed_iron.clearDrops();
mysticalagriculture_compressed_iron.addCategory("dirt");
mysticalagriculture_compressed_iron.addDrop(<item:mysticalagriculture:compressed_iron_essence>, 0.5, 4);
mysticalagriculture_compressed_iron.addDrop(<item:mysticalagriculture:compressed_iron_seeds>, 0.2);
mysticalagriculture_compressed_iron.addDrop(<item:mysticalagriculture:fertilized_essence>, 0.01, 1);
val mysticalagriculture_constantan = crops.getCrop("mysticalagriculture:crops/constantan");
mysticalagriculture_constantan.clearDrops();
mysticalagriculture_constantan.addCategory("dirt");
mysticalagriculture_constantan.addDrop(<item:mysticalagriculture:constantan_essence>, 0.5, 4);
mysticalagriculture_constantan.addDrop(<item:mysticalagriculture:constantan_seeds>, 0.2);
mysticalagriculture_constantan.addDrop(<item:mysticalagriculture:fertilized_essence>, 0.01, 1);
val mysticalagriculture_copper = crops.getCrop("mysticalagriculture:crops/copper");
mysticalagriculture_copper.clearDrops();
mysticalagriculture_copper.addCategory("dirt");
mysticalagriculture_copper.addDrop(<item:mysticalagriculture:copper_essence>, 0.5, 4);
mysticalagriculture_copper.addDrop(<item:mysticalagriculture:copper_seeds>, 0.2);
mysticalagriculture_copper.addDrop(<item:mysticalagriculture:fertilized_essence>, 0.01, 1);
val mysticalagriculture_coral = crops.getCrop("mysticalagriculture:crops/coral");
mysticalagriculture_coral.clearDrops();
mysticalagriculture_coral.addCategory("dirt");
mysticalagriculture_coral.addDrop(<item:mysticalagriculture:coral_essence>, 0.5, 4);
mysticalagriculture_coral.addDrop(<item:mysticalagriculture:coral_seeds>, 0.2);
mysticalagriculture_coral.addDrop(<item:mysticalagriculture:fertilized_essence>, 0.01, 1);
val mysticalagriculture_cow = crops.getCrop("mysticalagriculture:crops/cow");
mysticalagriculture_cow.clearDrops();
mysticalagriculture_cow.addCategory("dirt");
mysticalagriculture_cow.addDrop(<item:mysticalagriculture:cow_essence>, 0.5, 4);
mysticalagriculture_cow.addDrop(<item:mysticalagriculture:cow_seeds>, 0.2);
mysticalagriculture_cow.addDrop(<item:mysticalagriculture:fertilized_essence>, 0.01, 1);
val mysticalagriculture_creeper = crops.getCrop("mysticalagriculture:crops/creeper");
mysticalagriculture_creeper.clearDrops();
mysticalagriculture_creeper.addCategory("dirt");
mysticalagriculture_creeper.addDrop(<item:mysticalagriculture:creeper_essence>, 0.5, 4);
mysticalagriculture_creeper.addDrop(<item:mysticalagriculture:creeper_seeds>, 0.2);
mysticalagriculture_creeper.addDrop(<item:mysticalagriculture:fertilized_essence>, 0.01, 1);
val mysticalagriculture_diamond = crops.getCrop("mysticalagriculture:crops/diamond");
mysticalagriculture_diamond.clearDrops();
mysticalagriculture_diamond.addCategory("dirt");
mysticalagriculture_diamond.addDrop(<item:mysticalagriculture:diamond_essence>, 0.5, 4);
mysticalagriculture_diamond.addDrop(<item:mysticalagriculture:diamond_seeds>, 0.2);
mysticalagriculture_diamond.addDrop(<item:mysticalagriculture:fertilized_essence>, 0.01, 1);
val mysticalagriculture_dirt = crops.getCrop("mysticalagriculture:crops/dirt");
mysticalagriculture_dirt.clearDrops();
mysticalagriculture_dirt.addCategory("dirt");
mysticalagriculture_dirt.addDrop(<item:mysticalagriculture:dirt_essence>, 0.5, 4);
mysticalagriculture_dirt.addDrop(<item:mysticalagriculture:dirt_seeds>, 0.2);
mysticalagriculture_dirt.addDrop(<item:mysticalagriculture:fertilized_essence>, 0.01, 1);
val mysticalagriculture_dye = crops.getCrop("mysticalagriculture:crops/dye");
mysticalagriculture_dye.clearDrops();
mysticalagriculture_dye.addCategory("dirt");
mysticalagriculture_dye.addDrop(<item:mysticalagriculture:dye_essence>, 0.5, 4);
mysticalagriculture_dye.addDrop(<item:mysticalagriculture:dye_seeds>, 0.2);
mysticalagriculture_dye.addDrop(<item:mysticalagriculture:fertilized_essence>, 0.01, 1);
val mysticalagriculture_earth = crops.getCrop("mysticalagriculture:crops/earth");
mysticalagriculture_earth.clearDrops();
mysticalagriculture_earth.addCategory("dirt");
mysticalagriculture_earth.addDrop(<item:mysticalagriculture:earth_essence>, 0.5, 4);
mysticalagriculture_earth.addDrop(<item:mysticalagriculture:earth_seeds>, 0.2);
mysticalagriculture_earth.addDrop(<item:mysticalagriculture:fertilized_essence>, 0.01, 1);
val mysticalagriculture_electrum = crops.getCrop("mysticalagriculture:crops/electrum");
mysticalagriculture_electrum.clearDrops();
mysticalagriculture_electrum.addCategory("dirt");
mysticalagriculture_electrum.addDrop(<item:mysticalagriculture:electrum_essence>, 0.5, 4);
mysticalagriculture_electrum.addDrop(<item:mysticalagriculture:electrum_seeds>, 0.2);
mysticalagriculture_electrum.addDrop(<item:mysticalagriculture:fertilized_essence>, 0.01, 1);
val mysticalagriculture_elementium = crops.getCrop("mysticalagriculture:crops/elementium");
mysticalagriculture_elementium.clearDrops();
mysticalagriculture_elementium.addCategory("dirt");
mysticalagriculture_elementium.addDrop(<item:mysticalagriculture:elementium_essence>, 0.5, 4);
mysticalagriculture_elementium.addDrop(<item:mysticalagriculture:elementium_seeds>, 0.2);
mysticalagriculture_elementium.addDrop(<item:mysticalagriculture:fertilized_essence>, 0.01, 1);
val mysticalagriculture_emerald = crops.getCrop("mysticalagriculture:crops/emerald");
mysticalagriculture_emerald.clearDrops();
mysticalagriculture_emerald.addCategory("dirt");
mysticalagriculture_emerald.addDrop(<item:mysticalagriculture:emerald_essence>, 0.5, 4);
mysticalagriculture_emerald.addDrop(<item:mysticalagriculture:emerald_seeds>, 0.2);
mysticalagriculture_emerald.addDrop(<item:mysticalagriculture:fertilized_essence>, 0.01, 1);
val mysticalagriculture_end = crops.getCrop("mysticalagriculture:crops/end");
mysticalagriculture_end.clearDrops();
mysticalagriculture_end.addCategory("dirt");
mysticalagriculture_end.addDrop(<item:mysticalagriculture:end_essence>, 0.5, 4);
mysticalagriculture_end.addDrop(<item:mysticalagriculture:end_seeds>, 0.2);
mysticalagriculture_end.addDrop(<item:mysticalagriculture:fertilized_essence>, 0.01, 1);
val mysticalagriculture_enderium = crops.getCrop("mysticalagriculture:crops/enderium");
mysticalagriculture_enderium.clearDrops();
mysticalagriculture_enderium.addCategory("dirt");
mysticalagriculture_enderium.addDrop(<item:mysticalagriculture:enderium_essence>, 0.5, 4);
mysticalagriculture_enderium.addDrop(<item:mysticalagriculture:enderium_seeds>, 0.2);
mysticalagriculture_enderium.addDrop(<item:mysticalagriculture:fertilized_essence>, 0.01, 1);
val mysticalagriculture_enderman = crops.getCrop("mysticalagriculture:crops/enderman");
mysticalagriculture_enderman.clearDrops();
mysticalagriculture_enderman.addCategory("dirt");
mysticalagriculture_enderman.addDrop(<item:mysticalagriculture:enderman_essence>, 0.5, 4);
mysticalagriculture_enderman.addDrop(<item:mysticalagriculture:enderman_seeds>, 0.2);
mysticalagriculture_enderman.addDrop(<item:mysticalagriculture:fertilized_essence>, 0.01, 1);
val mysticalagriculture_ender_biotite = crops.getCrop("mysticalagriculture:crops/ender_biotite");
mysticalagriculture_ender_biotite.clearDrops();
mysticalagriculture_ender_biotite.addCategory("dirt");
mysticalagriculture_ender_biotite.addDrop(<item:mysticalagriculture:ender_biotite_essence>, 0.5, 4);
mysticalagriculture_ender_biotite.addDrop(<item:mysticalagriculture:ender_biotite_seeds>, 0.2);
mysticalagriculture_ender_biotite.addDrop(<item:mysticalagriculture:fertilized_essence>, 0.01, 1);
val mysticalagriculture_energized_steel = crops.getCrop("mysticalagriculture:crops/energized_steel");
mysticalagriculture_energized_steel.clearDrops();
mysticalagriculture_energized_steel.addCategory("dirt");
mysticalagriculture_energized_steel.addDrop(<item:mysticalagriculture:energized_steel_essence>, 0.5, 4);
mysticalagriculture_energized_steel.addDrop(<item:mysticalagriculture:energized_steel_seeds>, 0.2);
mysticalagriculture_energized_steel.addDrop(<item:mysticalagriculture:fertilized_essence>, 0.01, 1);
val mysticalagriculture_experience = crops.getCrop("mysticalagriculture:crops/experience");
mysticalagriculture_experience.clearDrops();
mysticalagriculture_experience.addCategory("dirt");
mysticalagriculture_experience.addDrop(<item:mysticalagriculture:experience_essence>, 0.5, 4);
mysticalagriculture_experience.addDrop(<item:mysticalagriculture:experience_seeds>, 0.2);
mysticalagriculture_experience.addDrop(<item:mysticalagriculture:fertilized_essence>, 0.01, 1);
val mysticalagriculture_fire = crops.getCrop("mysticalagriculture:crops/fire");
mysticalagriculture_fire.clearDrops();
mysticalagriculture_fire.addCategory("dirt");
mysticalagriculture_fire.addDrop(<item:mysticalagriculture:fire_essence>, 0.5, 4);
mysticalagriculture_fire.addDrop(<item:mysticalagriculture:fire_seeds>, 0.2);
mysticalagriculture_fire.addDrop(<item:mysticalagriculture:fertilized_essence>, 0.01, 1);
val mysticalagriculture_fish = crops.getCrop("mysticalagriculture:crops/fish");
mysticalagriculture_fish.clearDrops();
mysticalagriculture_fish.addCategory("dirt");
mysticalagriculture_fish.addDrop(<item:mysticalagriculture:fish_essence>, 0.5, 4);
mysticalagriculture_fish.addDrop(<item:mysticalagriculture:fish_seeds>, 0.2);
mysticalagriculture_fish.addDrop(<item:mysticalagriculture:fertilized_essence>, 0.01, 1);
val mysticalagriculture_fluix = crops.getCrop("mysticalagriculture:crops/fluix");
mysticalagriculture_fluix.clearDrops();
mysticalagriculture_fluix.addCategory("dirt");
mysticalagriculture_fluix.addDrop(<item:mysticalagriculture:fluix_essence>, 0.5, 4);
mysticalagriculture_fluix.addDrop(<item:mysticalagriculture:fluix_seeds>, 0.2);
mysticalagriculture_fluix.addDrop(<item:mysticalagriculture:fertilized_essence>, 0.01, 1);
val mysticalagriculture_ghast = crops.getCrop("mysticalagriculture:crops/ghast");
mysticalagriculture_ghast.clearDrops();
mysticalagriculture_ghast.addCategory("dirt");
mysticalagriculture_ghast.addDrop(<item:mysticalagriculture:ghast_essence>, 0.5, 4);
mysticalagriculture_ghast.addDrop(<item:mysticalagriculture:ghast_seeds>, 0.2);
mysticalagriculture_ghast.addDrop(<item:mysticalagriculture:fertilized_essence>, 0.01, 1);
val mysticalagriculture_glowstone = crops.getCrop("mysticalagriculture:crops/glowstone");
mysticalagriculture_glowstone.clearDrops();
mysticalagriculture_glowstone.addCategory("dirt");
mysticalagriculture_glowstone.addDrop(<item:mysticalagriculture:glowstone_essence>, 0.5, 4);
mysticalagriculture_glowstone.addDrop(<item:mysticalagriculture:glowstone_seeds>, 0.2);
mysticalagriculture_glowstone.addDrop(<item:mysticalagriculture:fertilized_essence>, 0.01, 1);
val mysticalagriculture_gold = crops.getCrop("mysticalagriculture:crops/gold");
mysticalagriculture_gold.clearDrops();
mysticalagriculture_gold.addCategory("dirt");
mysticalagriculture_gold.addDrop(<item:mysticalagriculture:gold_essence>, 0.5, 4);
mysticalagriculture_gold.addDrop(<item:mysticalagriculture:gold_seeds>, 0.2);
mysticalagriculture_gold.addDrop(<item:mysticalagriculture:fertilized_essence>, 0.01, 1);
val mysticalagriculture_graphite = crops.getCrop("mysticalagriculture:crops/graphite");
mysticalagriculture_graphite.clearDrops();
mysticalagriculture_graphite.addCategory("dirt");
mysticalagriculture_graphite.addDrop(<item:mysticalagriculture:graphite_essence>, 0.5, 4);
mysticalagriculture_graphite.addDrop(<item:mysticalagriculture:graphite_seeds>, 0.2);
mysticalagriculture_graphite.addDrop(<item:mysticalagriculture:fertilized_essence>, 0.01, 1);
val mysticalagriculture_honey = crops.getCrop("mysticalagriculture:crops/honey");
mysticalagriculture_honey.clearDrops();
mysticalagriculture_honey.addCategory("dirt");
mysticalagriculture_honey.addDrop(<item:mysticalagriculture:honey_essence>, 0.5, 4);
mysticalagriculture_honey.addDrop(<item:mysticalagriculture:honey_seeds>, 0.2);
mysticalagriculture_honey.addDrop(<item:mysticalagriculture:fertilized_essence>, 0.01, 1);
val mysticalagriculture_ice = crops.getCrop("mysticalagriculture:crops/ice");
mysticalagriculture_ice.clearDrops();
mysticalagriculture_ice.addCategory("dirt");
mysticalagriculture_ice.addDrop(<item:mysticalagriculture:ice_essence>, 0.5, 4);
mysticalagriculture_ice.addDrop(<item:mysticalagriculture:ice_seeds>, 0.2);
mysticalagriculture_ice.addDrop(<item:mysticalagriculture:fertilized_essence>, 0.01, 1);
val mysticalagriculture_inferium = crops.getCrop("mysticalagriculture:crops/inferium");
mysticalagriculture_inferium.clearDrops();
mysticalagriculture_inferium.addCategory("dirt");
mysticalagriculture_inferium.addDrop(<item:mysticalagriculture:inferium_essence>, 0.5, 4);
mysticalagriculture_inferium.addDrop(<item:mysticalagriculture:inferium_seeds>, 0.2);
mysticalagriculture_inferium.addDrop(<item:mysticalagriculture:fertilized_essence>, 0.01, 1);
val mysticalagriculture_invar = crops.getCrop("mysticalagriculture:crops/invar");
mysticalagriculture_invar.clearDrops();
mysticalagriculture_invar.addCategory("dirt");
mysticalagriculture_invar.addDrop(<item:mysticalagriculture:invar_essence>, 0.5, 4);
mysticalagriculture_invar.addDrop(<item:mysticalagriculture:invar_seeds>, 0.2);
mysticalagriculture_invar.addDrop(<item:mysticalagriculture:fertilized_essence>, 0.01, 1);
val mysticalagriculture_iridium = crops.getCrop("mysticalagriculture:crops/iridium");
mysticalagriculture_iridium.clearDrops();
mysticalagriculture_iridium.addCategory("dirt");
mysticalagriculture_iridium.addDrop(<item:mysticalagriculture:iridium_essence>, 0.5, 4);
mysticalagriculture_iridium.addDrop(<item:mysticalagriculture:iridium_seeds>, 0.2);
mysticalagriculture_iridium.addDrop(<item:mysticalagriculture:fertilized_essence>, 0.01, 1);
val mysticalagriculture_iron = crops.getCrop("mysticalagriculture:crops/iron");
mysticalagriculture_iron.clearDrops();
mysticalagriculture_iron.addCategory("dirt");
mysticalagriculture_iron.addDrop(<item:mysticalagriculture:iron_essence>, 0.5, 4);
mysticalagriculture_iron.addDrop(<item:mysticalagriculture:iron_seeds>, 0.2);
mysticalagriculture_iron.addDrop(<item:mysticalagriculture:fertilized_essence>, 0.01, 1);
val mysticalagriculture_lapis_lazuli = crops.getCrop("mysticalagriculture:crops/lapis_lazuli");
mysticalagriculture_lapis_lazuli.clearDrops();
mysticalagriculture_lapis_lazuli.addCategory("dirt");
mysticalagriculture_lapis_lazuli.addDrop(<item:mysticalagriculture:lapis_lazuli_essence>, 0.5, 4);
mysticalagriculture_lapis_lazuli.addDrop(<item:mysticalagriculture:lapis_lazuli_seeds>, 0.2);
mysticalagriculture_lapis_lazuli.addDrop(<item:mysticalagriculture:fertilized_essence>, 0.01, 1);
val mysticalagriculture_lead = crops.getCrop("mysticalagriculture:crops/lead");
mysticalagriculture_lead.clearDrops();
mysticalagriculture_lead.addCategory("dirt");
mysticalagriculture_lead.addDrop(<item:mysticalagriculture:lead_essence>, 0.5, 4);
mysticalagriculture_lead.addDrop(<item:mysticalagriculture:lead_seeds>, 0.2);
mysticalagriculture_lead.addDrop(<item:mysticalagriculture:fertilized_essence>, 0.01, 1);
val mysticalagriculture_lumium = crops.getCrop("mysticalagriculture:crops/lumium");
mysticalagriculture_lumium.clearDrops();
mysticalagriculture_lumium.addCategory("dirt");
mysticalagriculture_lumium.addDrop(<item:mysticalagriculture:lumium_essence>, 0.5, 4);
mysticalagriculture_lumium.addDrop(<item:mysticalagriculture:lumium_seeds>, 0.2);
mysticalagriculture_lumium.addDrop(<item:mysticalagriculture:fertilized_essence>, 0.01, 1);
val mysticalagriculture_manasteel = crops.getCrop("mysticalagriculture:crops/manasteel");
mysticalagriculture_manasteel.clearDrops();
mysticalagriculture_manasteel.addCategory("dirt");
mysticalagriculture_manasteel.addDrop(<item:mysticalagriculture:manasteel_essence>, 0.5, 4);
mysticalagriculture_manasteel.addDrop(<item:mysticalagriculture:manasteel_seeds>, 0.2);
mysticalagriculture_manasteel.addDrop(<item:mysticalagriculture:fertilized_essence>, 0.01, 1);
val mysticalagriculture_mithril = crops.getCrop("mysticalagriculture:crops/mithril");
mysticalagriculture_mithril.clearDrops();
mysticalagriculture_mithril.addCategory("dirt");
mysticalagriculture_mithril.addDrop(<item:mysticalagriculture:mithril_essence>, 0.5, 4);
mysticalagriculture_mithril.addDrop(<item:mysticalagriculture:mithril_seeds>, 0.2);
mysticalagriculture_mithril.addDrop(<item:mysticalagriculture:fertilized_essence>, 0.01, 1);
val mysticalagriculture_mystical_flower = crops.getCrop("mysticalagriculture:crops/mystical_flower");
mysticalagriculture_mystical_flower.clearDrops();
mysticalagriculture_mystical_flower.addCategory("dirt");
mysticalagriculture_mystical_flower.addDrop(<item:mysticalagriculture:mystical_flower_essence>, 0.5, 4);
mysticalagriculture_mystical_flower.addDrop(<item:mysticalagriculture:mystical_flower_seeds>, 0.2);
mysticalagriculture_mystical_flower.addDrop(<item:mysticalagriculture:fertilized_essence>, 0.01, 1);
val mysticalagriculture_nature = crops.getCrop("mysticalagriculture:crops/nature");
mysticalagriculture_nature.clearDrops();
mysticalagriculture_nature.addCategory("dirt");
mysticalagriculture_nature.addDrop(<item:mysticalagriculture:nature_essence>, 0.5, 4);
mysticalagriculture_nature.addDrop(<item:mysticalagriculture:nature_seeds>, 0.2);
mysticalagriculture_nature.addDrop(<item:mysticalagriculture:fertilized_essence>, 0.01, 1);
val mysticalagriculture_nether = crops.getCrop("mysticalagriculture:crops/nether");
mysticalagriculture_nether.clearDrops();
mysticalagriculture_nether.addCategory("dirt");
mysticalagriculture_nether.addDrop(<item:mysticalagriculture:nether_essence>, 0.5, 4);
mysticalagriculture_nether.addDrop(<item:mysticalagriculture:nether_seeds>, 0.2);
mysticalagriculture_nether.addDrop(<item:mysticalagriculture:fertilized_essence>, 0.01, 1);
val mysticalagriculture_netherite = crops.getCrop("mysticalagriculture:crops/netherite");
mysticalagriculture_netherite.clearDrops();
mysticalagriculture_netherite.addCategory("dirt");
mysticalagriculture_netherite.addDrop(<item:mysticalagriculture:netherite_essence>, 0.5, 4);
mysticalagriculture_netherite.addDrop(<item:mysticalagriculture:netherite_seeds>, 0.2);
mysticalagriculture_netherite.addDrop(<item:mysticalagriculture:fertilized_essence>, 0.01, 1);
val mysticalagriculture_nether_quartz = crops.getCrop("mysticalagriculture:crops/nether_quartz");
mysticalagriculture_nether_quartz.clearDrops();
mysticalagriculture_nether_quartz.addCategory("dirt");
mysticalagriculture_nether_quartz.addDrop(<item:mysticalagriculture:nether_quartz_essence>, 0.5, 4);
mysticalagriculture_nether_quartz.addDrop(<item:mysticalagriculture:nether_quartz_seeds>, 0.2);
mysticalagriculture_nether_quartz.addDrop(<item:mysticalagriculture:fertilized_essence>, 0.01, 1);
val mysticalagriculture_nether_star = crops.getCrop("mysticalagriculture:crops/nether_star");
mysticalagriculture_nether_star.clearDrops();
mysticalagriculture_nether_star.addCategory("dirt");
mysticalagriculture_nether_star.addDrop(<item:mysticalagriculture:nether_star_essence>, 0.5, 4);
mysticalagriculture_nether_star.addDrop(<item:mysticalagriculture:nether_star_seeds>, 0.2);
mysticalagriculture_nether_star.addDrop(<item:mysticalagriculture:fertilized_essence>, 0.01, 1);
val mysticalagriculture_nickel = crops.getCrop("mysticalagriculture:crops/nickel");
mysticalagriculture_nickel.clearDrops();
mysticalagriculture_nickel.addCategory("dirt");
mysticalagriculture_nickel.addDrop(<item:mysticalagriculture:nickel_essence>, 0.5, 4);
mysticalagriculture_nickel.addDrop(<item:mysticalagriculture:nickel_seeds>, 0.2);
mysticalagriculture_nickel.addDrop(<item:mysticalagriculture:fertilized_essence>, 0.01, 1);
val mysticalagriculture_obsidian = crops.getCrop("mysticalagriculture:crops/obsidian");
mysticalagriculture_obsidian.clearDrops();
mysticalagriculture_obsidian.addCategory("dirt");
mysticalagriculture_obsidian.addDrop(<item:mysticalagriculture:obsidian_essence>, 0.5, 4);
mysticalagriculture_obsidian.addDrop(<item:mysticalagriculture:obsidian_seeds>, 0.2);
mysticalagriculture_obsidian.addDrop(<item:mysticalagriculture:fertilized_essence>, 0.01, 1);
val mysticalagriculture_osmium = crops.getCrop("mysticalagriculture:crops/osmium");
mysticalagriculture_osmium.clearDrops();
mysticalagriculture_osmium.addCategory("dirt");
mysticalagriculture_osmium.addDrop(<item:mysticalagriculture:osmium_essence>, 0.5, 4);
mysticalagriculture_osmium.addDrop(<item:mysticalagriculture:osmium_seeds>, 0.2);
mysticalagriculture_osmium.addDrop(<item:mysticalagriculture:fertilized_essence>, 0.01, 1);
val mysticalagriculture_pig = crops.getCrop("mysticalagriculture:crops/pig");
mysticalagriculture_pig.clearDrops();
mysticalagriculture_pig.addCategory("dirt");
mysticalagriculture_pig.addDrop(<item:mysticalagriculture:pig_essence>, 0.5, 4);
mysticalagriculture_pig.addDrop(<item:mysticalagriculture:pig_seeds>, 0.2);
mysticalagriculture_pig.addDrop(<item:mysticalagriculture:fertilized_essence>, 0.01, 1);
val mysticalagriculture_platinum = crops.getCrop("mysticalagriculture:crops/platinum");
mysticalagriculture_platinum.clearDrops();
mysticalagriculture_platinum.addCategory("dirt");
mysticalagriculture_platinum.addDrop(<item:mysticalagriculture:platinum_essence>, 0.5, 4);
mysticalagriculture_platinum.addDrop(<item:mysticalagriculture:platinum_seeds>, 0.2);
mysticalagriculture_platinum.addDrop(<item:mysticalagriculture:fertilized_essence>, 0.01, 1);
val mysticalagriculture_prismarine = crops.getCrop("mysticalagriculture:crops/prismarine");
mysticalagriculture_prismarine.clearDrops();
mysticalagriculture_prismarine.addCategory("dirt");
mysticalagriculture_prismarine.addDrop(<item:mysticalagriculture:prismarine_essence>, 0.5, 4);
mysticalagriculture_prismarine.addDrop(<item:mysticalagriculture:prismarine_seeds>, 0.2);
mysticalagriculture_prismarine.addDrop(<item:mysticalagriculture:fertilized_essence>, 0.01, 1);
val mysticalagriculture_quartz_enriched_iron = crops.getCrop("mysticalagriculture:crops/quartz_enriched_iron");
mysticalagriculture_quartz_enriched_iron.clearDrops();
mysticalagriculture_quartz_enriched_iron.addCategory("dirt");
mysticalagriculture_quartz_enriched_iron.addDrop(<item:mysticalagriculture:quartz_enriched_iron_essence>, 0.5, 4);
mysticalagriculture_quartz_enriched_iron.addDrop(<item:mysticalagriculture:quartz_enriched_iron_seeds>, 0.2);
mysticalagriculture_quartz_enriched_iron.addDrop(<item:mysticalagriculture:fertilized_essence>, 0.01, 1);
val mysticalagriculture_rabbit = crops.getCrop("mysticalagriculture:crops/rabbit");
mysticalagriculture_rabbit.clearDrops();
mysticalagriculture_rabbit.addCategory("dirt");
mysticalagriculture_rabbit.addDrop(<item:mysticalagriculture:rabbit_essence>, 0.5, 4);
mysticalagriculture_rabbit.addDrop(<item:mysticalagriculture:rabbit_seeds>, 0.2);
mysticalagriculture_rabbit.addDrop(<item:mysticalagriculture:fertilized_essence>, 0.01, 1);
val mysticalagriculture_redstone = crops.getCrop("mysticalagriculture:crops/redstone");
mysticalagriculture_redstone.clearDrops();
mysticalagriculture_redstone.addCategory("dirt");
mysticalagriculture_redstone.addDrop(<item:mysticalagriculture:redstone_essence>, 0.5, 4);
mysticalagriculture_redstone.addDrop(<item:mysticalagriculture:redstone_seeds>, 0.2);
mysticalagriculture_redstone.addDrop(<item:mysticalagriculture:fertilized_essence>, 0.01, 1);
val mysticalagriculture_refined_glowstone = crops.getCrop("mysticalagriculture:crops/refined_glowstone");
mysticalagriculture_refined_glowstone.clearDrops();
mysticalagriculture_refined_glowstone.addCategory("dirt");
mysticalagriculture_refined_glowstone.addDrop(<item:mysticalagriculture:refined_glowstone_essence>, 0.5, 4);
mysticalagriculture_refined_glowstone.addDrop(<item:mysticalagriculture:refined_glowstone_seeds>, 0.2);
mysticalagriculture_refined_glowstone.addDrop(<item:mysticalagriculture:fertilized_essence>, 0.01, 1);
val mysticalagriculture_refined_obsidian = crops.getCrop("mysticalagriculture:crops/refined_obsidian");
mysticalagriculture_refined_obsidian.clearDrops();
mysticalagriculture_refined_obsidian.addCategory("dirt");
mysticalagriculture_refined_obsidian.addDrop(<item:mysticalagriculture:refined_obsidian_essence>, 0.5, 4);
mysticalagriculture_refined_obsidian.addDrop(<item:mysticalagriculture:refined_obsidian_seeds>, 0.2);
mysticalagriculture_refined_obsidian.addDrop(<item:mysticalagriculture:fertilized_essence>, 0.01, 1);
val mysticalagriculture_rubber = crops.getCrop("mysticalagriculture:crops/rubber");
mysticalagriculture_rubber.clearDrops();
mysticalagriculture_rubber.addCategory("dirt");
mysticalagriculture_rubber.addDrop(<item:mysticalagriculture:rubber_essence>, 0.5, 4);
mysticalagriculture_rubber.addDrop(<item:mysticalagriculture:rubber_seeds>, 0.2);
mysticalagriculture_rubber.addDrop(<item:mysticalagriculture:fertilized_essence>, 0.01, 1);
val mysticalagriculture_saltpeter = crops.getCrop("mysticalagriculture:crops/saltpeter");
mysticalagriculture_saltpeter.clearDrops();
mysticalagriculture_saltpeter.addCategory("dirt");
mysticalagriculture_saltpeter.addDrop(<item:mysticalagriculture:saltpeter_essence>, 0.5, 4);
mysticalagriculture_saltpeter.addDrop(<item:mysticalagriculture:saltpeter_seeds>, 0.2);
mysticalagriculture_saltpeter.addDrop(<item:mysticalagriculture:fertilized_essence>, 0.01, 1);
val mysticalagriculture_sheep = crops.getCrop("mysticalagriculture:crops/sheep");
mysticalagriculture_sheep.clearDrops();
mysticalagriculture_sheep.addCategory("dirt");
mysticalagriculture_sheep.addDrop(<item:mysticalagriculture:sheep_essence>, 0.5, 4);
mysticalagriculture_sheep.addDrop(<item:mysticalagriculture:sheep_seeds>, 0.2);
mysticalagriculture_sheep.addDrop(<item:mysticalagriculture:fertilized_essence>, 0.01, 1);
val mysticalagriculture_signalum = crops.getCrop("mysticalagriculture:crops/signalum");
mysticalagriculture_signalum.clearDrops();
mysticalagriculture_signalum.addCategory("dirt");
mysticalagriculture_signalum.addDrop(<item:mysticalagriculture:signalum_essence>, 0.5, 4);
mysticalagriculture_signalum.addDrop(<item:mysticalagriculture:signalum_seeds>, 0.2);
mysticalagriculture_signalum.addDrop(<item:mysticalagriculture:fertilized_essence>, 0.01, 1);
val mysticalagriculture_silicon = crops.getCrop("mysticalagriculture:crops/silicon");
mysticalagriculture_silicon.clearDrops();
mysticalagriculture_silicon.addCategory("dirt");
mysticalagriculture_silicon.addDrop(<item:mysticalagriculture:silicon_essence>, 0.5, 4);
mysticalagriculture_silicon.addDrop(<item:mysticalagriculture:silicon_seeds>, 0.2);
mysticalagriculture_silicon.addDrop(<item:mysticalagriculture:fertilized_essence>, 0.01, 1);
val mysticalagriculture_silver = crops.getCrop("mysticalagriculture:crops/silver");
mysticalagriculture_silver.clearDrops();
mysticalagriculture_silver.addCategory("dirt");
mysticalagriculture_silver.addDrop(<item:mysticalagriculture:silver_essence>, 0.5, 4);
mysticalagriculture_silver.addDrop(<item:mysticalagriculture:silver_seeds>, 0.2);
mysticalagriculture_silver.addDrop(<item:mysticalagriculture:fertilized_essence>, 0.01, 1);
val mysticalagriculture_skeleton = crops.getCrop("mysticalagriculture:crops/skeleton");
mysticalagriculture_skeleton.clearDrops();
mysticalagriculture_skeleton.addCategory("dirt");
mysticalagriculture_skeleton.addDrop(<item:mysticalagriculture:skeleton_essence>, 0.5, 4);
mysticalagriculture_skeleton.addDrop(<item:mysticalagriculture:skeleton_seeds>, 0.2);
mysticalagriculture_skeleton.addDrop(<item:mysticalagriculture:fertilized_essence>, 0.01, 1);
val mysticalagriculture_sky_stone = crops.getCrop("mysticalagriculture:crops/sky_stone");
mysticalagriculture_sky_stone.clearDrops();
mysticalagriculture_sky_stone.addCategory("dirt");
mysticalagriculture_sky_stone.addDrop(<item:mysticalagriculture:sky_stone_essence>, 0.5, 4);
mysticalagriculture_sky_stone.addDrop(<item:mysticalagriculture:sky_stone_seeds>, 0.2);
mysticalagriculture_sky_stone.addDrop(<item:mysticalagriculture:fertilized_essence>, 0.01, 1);
val mysticalagriculture_slime = crops.getCrop("mysticalagriculture:crops/slime");
mysticalagriculture_slime.clearDrops();
mysticalagriculture_slime.addCategory("dirt");
mysticalagriculture_slime.addDrop(<item:mysticalagriculture:slime_essence>, 0.5, 4);
mysticalagriculture_slime.addDrop(<item:mysticalagriculture:slime_seeds>, 0.2);
mysticalagriculture_slime.addDrop(<item:mysticalagriculture:fertilized_essence>, 0.01, 1);
val mysticalagriculture_spider = crops.getCrop("mysticalagriculture:crops/spider");
mysticalagriculture_spider.clearDrops();
mysticalagriculture_spider.addCategory("dirt");
mysticalagriculture_spider.addDrop(<item:mysticalagriculture:spider_essence>, 0.5, 4);
mysticalagriculture_spider.addDrop(<item:mysticalagriculture:spider_seeds>, 0.2);
mysticalagriculture_spider.addDrop(<item:mysticalagriculture:fertilized_essence>, 0.01, 1);
val mysticalagriculture_spirited_crystal = crops.getCrop("mysticalagriculture:crops/spirited_crystal");
mysticalagriculture_spirited_crystal.clearDrops();
mysticalagriculture_spirited_crystal.addCategory("dirt");
mysticalagriculture_spirited_crystal.addDrop(<item:mysticalagriculture:spirited_crystal_essence>, 0.5, 4);
mysticalagriculture_spirited_crystal.addDrop(<item:mysticalagriculture:spirited_crystal_seeds>, 0.2);
mysticalagriculture_spirited_crystal.addDrop(<item:mysticalagriculture:fertilized_essence>, 0.01, 1);
val mysticalagriculture_squid = crops.getCrop("mysticalagriculture:crops/squid");
mysticalagriculture_squid.clearDrops();
mysticalagriculture_squid.addCategory("dirt");
mysticalagriculture_squid.addDrop(<item:mysticalagriculture:squid_essence>, 0.5, 4);
mysticalagriculture_squid.addDrop(<item:mysticalagriculture:squid_seeds>, 0.2);
mysticalagriculture_squid.addDrop(<item:mysticalagriculture:fertilized_essence>, 0.01, 1);
val mysticalagriculture_steel = crops.getCrop("mysticalagriculture:crops/steel");
mysticalagriculture_steel.clearDrops();
mysticalagriculture_steel.addCategory("dirt");
mysticalagriculture_steel.addDrop(<item:mysticalagriculture:steel_essence>, 0.5, 4);
mysticalagriculture_steel.addDrop(<item:mysticalagriculture:steel_seeds>, 0.2);
mysticalagriculture_steel.addDrop(<item:mysticalagriculture:fertilized_essence>, 0.01, 1);
val mysticalagriculture_stone = crops.getCrop("mysticalagriculture:crops/stone");
mysticalagriculture_stone.clearDrops();
mysticalagriculture_stone.addCategory("dirt");
mysticalagriculture_stone.addDrop(<item:mysticalagriculture:stone_essence>, 0.5, 4);
mysticalagriculture_stone.addDrop(<item:mysticalagriculture:stone_seeds>, 0.2);
mysticalagriculture_stone.addDrop(<item:mysticalagriculture:fertilized_essence>, 0.01, 1);
val mysticalagriculture_sulfur = crops.getCrop("mysticalagriculture:crops/sulfur");
mysticalagriculture_sulfur.clearDrops();
mysticalagriculture_sulfur.addCategory("dirt");
mysticalagriculture_sulfur.addDrop(<item:mysticalagriculture:sulfur_essence>, 0.5, 4);
mysticalagriculture_sulfur.addDrop(<item:mysticalagriculture:sulfur_seeds>, 0.2);
mysticalagriculture_sulfur.addDrop(<item:mysticalagriculture:fertilized_essence>, 0.01, 1);
val mysticalagriculture_terrasteel = crops.getCrop("mysticalagriculture:crops/terrasteel");
mysticalagriculture_terrasteel.clearDrops();
mysticalagriculture_terrasteel.addCategory("dirt");
mysticalagriculture_terrasteel.addDrop(<item:mysticalagriculture:terrasteel_essence>, 0.5, 4);
mysticalagriculture_terrasteel.addDrop(<item:mysticalagriculture:terrasteel_seeds>, 0.2);
mysticalagriculture_terrasteel.addDrop(<item:mysticalagriculture:fertilized_essence>, 0.01, 1);
val mysticalagriculture_tin = crops.getCrop("mysticalagriculture:crops/tin");
mysticalagriculture_tin.clearDrops();
mysticalagriculture_tin.addCategory("dirt");
mysticalagriculture_tin.addDrop(<item:mysticalagriculture:tin_essence>, 0.5, 4);
mysticalagriculture_tin.addDrop(<item:mysticalagriculture:tin_seeds>, 0.2);
mysticalagriculture_tin.addDrop(<item:mysticalagriculture:fertilized_essence>, 0.01, 1);
val mysticalagriculture_titanium = crops.getCrop("mysticalagriculture:crops/titanium");
mysticalagriculture_titanium.clearDrops();
mysticalagriculture_titanium.addCategory("dirt");
mysticalagriculture_titanium.addDrop(<item:mysticalagriculture:titanium_essence>, 0.5, 4);
mysticalagriculture_titanium.addDrop(<item:mysticalagriculture:titanium_seeds>, 0.2);
mysticalagriculture_titanium.addDrop(<item:mysticalagriculture:fertilized_essence>, 0.01, 1);
val mysticalagriculture_tungsten = crops.getCrop("mysticalagriculture:crops/tungsten");
mysticalagriculture_tungsten.clearDrops();
mysticalagriculture_tungsten.addCategory("dirt");
mysticalagriculture_tungsten.addDrop(<item:mysticalagriculture:tungsten_essence>, 0.5, 4);
mysticalagriculture_tungsten.addDrop(<item:mysticalagriculture:tungsten_seeds>, 0.2);
mysticalagriculture_tungsten.addDrop(<item:mysticalagriculture:fertilized_essence>, 0.01, 1);
val mysticalagriculture_turtle = crops.getCrop("mysticalagriculture:crops/turtle");
mysticalagriculture_turtle.clearDrops();
mysticalagriculture_turtle.addCategory("dirt");
mysticalagriculture_turtle.addDrop(<item:mysticalagriculture:turtle_essence>, 0.5, 4);
mysticalagriculture_turtle.addDrop(<item:mysticalagriculture:turtle_seeds>, 0.2);
mysticalagriculture_turtle.addDrop(<item:mysticalagriculture:fertilized_essence>, 0.01, 1);
val mysticalagriculture_uraninite = crops.getCrop("mysticalagriculture:crops/uraninite");
mysticalagriculture_uraninite.clearDrops();
mysticalagriculture_uraninite.addCategory("dirt");
mysticalagriculture_uraninite.addDrop(<item:mysticalagriculture:uraninite_essence>, 0.5, 4);
mysticalagriculture_uraninite.addDrop(<item:mysticalagriculture:uraninite_seeds>, 0.2);
mysticalagriculture_uraninite.addDrop(<item:mysticalagriculture:fertilized_essence>, 0.01, 1);
val mysticalagriculture_uranium = crops.getCrop("mysticalagriculture:crops/uranium");
mysticalagriculture_uranium.clearDrops();
mysticalagriculture_uranium.addCategory("dirt");
mysticalagriculture_uranium.addDrop(<item:mysticalagriculture:uranium_essence>, 0.5, 4);
mysticalagriculture_uranium.addDrop(<item:mysticalagriculture:uranium_seeds>, 0.2);
mysticalagriculture_uranium.addDrop(<item:mysticalagriculture:fertilized_essence>, 0.01, 1);
val mysticalagriculture_water = crops.getCrop("mysticalagriculture:crops/water");
mysticalagriculture_water.clearDrops();
mysticalagriculture_water.addCategory("dirt");
mysticalagriculture_water.addDrop(<item:mysticalagriculture:water_essence>, 0.5, 4);
mysticalagriculture_water.addDrop(<item:mysticalagriculture:water_seeds>, 0.2);
mysticalagriculture_water.addDrop(<item:mysticalagriculture:fertilized_essence>, 0.01, 1);
val mysticalagriculture_wither_skeleton = crops.getCrop("mysticalagriculture:crops/wither_skeleton");
mysticalagriculture_wither_skeleton.clearDrops();
mysticalagriculture_wither_skeleton.addCategory("dirt");
mysticalagriculture_wither_skeleton.addDrop(<item:mysticalagriculture:wither_skeleton_essence>, 0.5, 4);
mysticalagriculture_wither_skeleton.addDrop(<item:mysticalagriculture:wither_skeleton_seeds>, 0.2);
mysticalagriculture_wither_skeleton.addDrop(<item:mysticalagriculture:fertilized_essence>, 0.01, 1);
val mysticalagriculture_wood = crops.getCrop("mysticalagriculture:crops/wood");
mysticalagriculture_wood.clearDrops();
mysticalagriculture_wood.addCategory("dirt");
mysticalagriculture_wood.addDrop(<item:mysticalagriculture:wood_essence>, 0.5, 4);
mysticalagriculture_wood.addDrop(<item:mysticalagriculture:wood_seeds>, 0.2);
mysticalagriculture_wood.addDrop(<item:mysticalagriculture:fertilized_essence>, 0.01, 1);
val mysticalagriculture_zinc = crops.getCrop("mysticalagriculture:crops/zinc");
mysticalagriculture_zinc.clearDrops();
mysticalagriculture_zinc.addCategory("dirt");
mysticalagriculture_zinc.addDrop(<item:mysticalagriculture:zinc_essence>, 0.5, 4);
mysticalagriculture_zinc.addDrop(<item:mysticalagriculture:zinc_seeds>, 0.2);
mysticalagriculture_zinc.addDrop(<item:mysticalagriculture:fertilized_essence>, 0.01, 1);
val mysticalagriculture_zombie = crops.getCrop("mysticalagriculture:crops/zombie");
mysticalagriculture_zombie.clearDrops();
mysticalagriculture_zombie.addCategory("dirt");
mysticalagriculture_zombie.addDrop(<item:mysticalagriculture:zombie_essence>, 0.5, 4);
mysticalagriculture_zombie.addDrop(<item:mysticalagriculture:zombie_seeds>, 0.2);
mysticalagriculture_zombie.addDrop(<item:mysticalagriculture:fertilized_essence>, 0.01, 1);